### ISSUE TITLE
Network Importer Fails to import VLANs with same id at same site

### ISSUE THREAD

**Issue by nniehoff** [networktocode/network-importer#101]
### Environment
* Python version:  3.7.5
* Network Importer version:  Early

### Steps to Reproduce
1.  In netbox create a site with 2 vlans with the same ID, different prefixes
2. Run network importer to import that site
3.

### Expected Behavior
Both VLANs should be imported

### Observed Behavior
```
Traceback (most recent call last):
  File "/usr/local/bin/network-importer", line 5, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/source/network_importer/cli.py", line 103, in main
    ni.init(limit=limit)
  File "/source/network_importer/performance.py", line 83, in timed
    result = method(*args, **kw)
  File "/source/network_importer/main.py", line 156, in init
    self.sot.init()
  File "/source/network_importer/adapters/netbox_api/adapter.py", line 97, in init
    self.import_netbox_vlan(site)
  File "/source/network_importer/adapters/netbox_api/adapter.py", line 153, in import_netbox_vlan
    self.add(vlan)
  File "/source/dsync/__init__.py", line 461, in add
    raise ObjectAlreadyExist(f"Object {uid} already present")
dsync.exceptions.ObjectAlreadyExist: Object site1__1000 already present
```

**Comment by jvanderaa** [comment]
Looks like this may be resolved. @nniehoff
