### ISSUE TITLE
Import device with management IP

### ISSUE THREAD

**Issue by nitzan-tz** [networktocode/network-importer#150]
### Environment
* Python version:  python3.7
* Network Importer version:  2.0b2 (Docker latest )

When i am importing to netbox it cant delete management IP address from netbox but it try to recreate it and failed

2020-12-07 21:18:48,479 - network-importer - INFO - Updated Prefix 192.168.5.0/24 (1) in NetBox
2020-12-07 21:18:48,649 - network-importer - WARNING - Unable to delete IP Address 192.168.5.200/24 on leaf1-a-lab, because it's currently the management IP address
2020-12-07 21:18:48,660 - diffsync - WARNING - 2020-12-07 21:18.48 [warning  ] Non-fatal failure encountered  [diffsync] action=delete diffs={'src': {}, 'dst': {'interface_name': 'vme', 'device_name': 'leaf1-a-lab'}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=ip_address src=<Network> status=failure unique_id=192.168.5.200/24
2020-12-07 21:18:48,660 - diffsync - WARNING - 2020-12-07 21:18.48 [warning  ] Not syncing children           [diffsync] action=delete diffs={'src': {}, 'dst': {'interface_name': 'vme', 'device_name': 'leaf1-a-lab'}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=ip_address src=<Network> unique_id=192.168.5.200/24
2020-12-07 21:18:48,661 - diffsync - ERROR - 2020-12-07 21:18.48 [error    ] Failed to create ip_address {'address': '192.168.5.200/24'} - it exists! [diffsync] action=create diffs={'src': {'interface_name': 'vme.0', 'device_name': 'leaf1-a-lab'}, 'dst': {}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=ip_address src=<Network> status=error unique_id=192.168.5.200/24
Traceback (most recent call last):
  File "/usr/local/bin/network-importer", line 5, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/local/network_importer/cli.py", line 111, in apply
    ni.sync()
  File "/local/network_importer/main.py", line 169, in sync
    self.sot.sync_from(self.network, diff_class=NetworkImporterDiff)
  File "/usr/local/lib/python3.7/site-packages/diffsync/__init__.py", line 484, in sync_from
    self._sync_from_diff_element(child, flags=flags, logger=log)
  File "/usr/local/lib/python3.7/site-packages/diffsync/__init__.py", line 577, in _sync_from_diff_element
    self._sync_from_diff_element(child, flags=flags, parent_model=obj, logger=logger)
  File "/usr/local/lib/python3.7/site-packages/diffsync/__init__.py", line 577, in _sync_from_diff_element
    self._sync_from_diff_element(child, flags=flags, parent_model=obj, logger=logger)
  File "/usr/local/lib/python3.7/site-packages/diffsync/__init__.py", line 533, in _sync_from_diff_element
    raise ObjectNotCreated(f"Failed to create {object_class.get_type()} {element.keys} - it exists!")
diffsync.exceptions.ObjectNotCreated: Failed to create ip_address {'address': '192.168.5.200/24'} - it exists!

### Steps to Reproduce
1. Have device with management ip in netbox and try to import it
2.
3.

### Expected Behavior
It should ignore this prefix if it cant create it

### Observed Behavior
It throw a exception and exit

**Comment by dgarros** [comment]
Hi @nitzan-tz thanks for testing this project

Looks like you are running a non-compatible version of DiffSync, the current project requires 1.0.0 to work and my guess is you are running 1.1.0. This was possible because the version of diffsync required wasn't properly defined so pip automatically installed the latest one. 
I just published a new beta 3 release that should fix that.  

Please can you try again with the latest release or downgrade diffsync to 1.0.0

thanks

**Comment by nitzan-tz** [comment]
Hi @dgarros 

I did a fresh install via pip but I am getting the same issue 
BTW packaging module is missing from pip requirements 

2020-12-08 19:14:50,486 - network-importer - WARNING - Unable to update Vlan lab__2502 in Netbox ({"detail":"Method \"PATCH\" not allowed."})
2020-12-08 19:14:50,486 - diffsync - WARNING - 2020-12-08 19:14.50 [warning  ] Non-fatal failure encountered  [diffsync] action=update diffs={'src': {'associated_devices': ['spine1-a-lab', 'spine5-g-lab']}, 'dst': {'associated_devices': []}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=vlan src=<Network> status=failure unique_id=lab__2502
2020-12-08 19:14:50,487 - diffsync - WARNING - 2020-12-08 19:14.50 [warning  ] Not syncing children           [diffsync] action=update diffs={'src': {'associated_devices': ['spine1-a-lab', 'spine5-g-lab']}, 'dst': {'associated_devices': []}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=vlan src=<Network> unique_id=lab__2502
2020-12-08 19:14:50,854 - network-importer - INFO - Updated Prefix 192.168.5.0/24 (1) in NetBox
2020-12-08 19:14:50,952 - network-importer - WARNING - Unable to delete IP Address 192.168.5.200/24 on leaf1-a-lab, because it's currently the management IP address
2020-12-08 19:14:50,953 - diffsync - WARNING - 2020-12-08 19:14.50 [warning  ] Non-fatal failure encountered  [diffsync] action=delete diffs={'src': {}, 'dst': {'interface_name': 'vme', 'device_name': 'leaf1-a-lab'}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=ip_address src=<Network> status=failure unique_id=192.168.5.200/24
2020-12-08 19:14:50,953 - diffsync - WARNING - 2020-12-08 19:14.50 [warning  ] Not syncing children           [diffsync] action=delete diffs={'src': {}, 'dst': {'interface_name': 'vme', 'device_name': 'leaf1-a-lab'}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=ip_address src=<Network> unique_id=192.168.5.200/24
2020-12-08 19:14:50,954 - diffsync - ERROR - 2020-12-08 19:14.50 [error    ] Failed to create ip_address {'address': '192.168.5.200/24'} - it exists! [diffsync] action=create diffs={'src': {'interface_name': 'vme.0', 'device_name': 'leaf1-a-lab'}, 'dst': {}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=ip_address src=<Network> status=error unique_id=192.168.5.200/24
Traceback (most recent call last):
  File "/usr/local/bin/network-importer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/network_importer/cli.py", line 111, in apply
    ni.sync()
  File "/usr/local/lib/python3.8/dist-packages/network_importer/main.py", line 169, in sync
    self.sot.sync_from(self.network, diff_class=NetworkImporterDiff)
  File "/usr/local/lib/python3.8/dist-packages/diffsync/__init__.py", line 484, in sync_from
    self._sync_from_diff_element(child, flags=flags, logger=log)
  File "/usr/local/lib/python3.8/dist-packages/diffsync/__init__.py", line 577, in _sync_from_diff_element
    self._sync_from_diff_element(child, flags=flags, parent_model=obj, logger=logger)
  File "/usr/local/lib/python3.8/dist-packages/diffsync/__init__.py", line 577, in _sync_from_diff_element
    self._sync_from_diff_element(child, flags=flags, parent_model=obj, logger=logger)
  File "/usr/local/lib/python3.8/dist-packages/diffsync/__init__.py", line 533, in _sync_from_diff_element
    raise ObjectNotCreated(f"Failed to create {object_class.get_type()} {element.keys} - it exists!")
diffsync.exceptions.ObjectNotCreated: Failed to create ip_address {'address': '192.168.5.200/24'} - it exists!
root@automation-ng:~/network-importer/examples/oasis#

**Comment by jvanderaa** [comment]
Closing issue based on age.
