### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by CyrielRct** [networktocode/network-importer#157]
### Environment
* Run in Docker based on docker-compose of the project
* Python version:  "3.7.7"
* Network Importer version:  (2, 0, "0-beta3")
* Netbox version : v2.9.7

### Steps to Reproduce
1. Configuration inventory section filters on one device (tried one in VC and no VC same error) 
2. network-importer inventory --config /source/config/network_importer.toml

### Behavior

```
[root@mtlbmepvlxcdkr01 network-importer]# docker exec -ti network_importer network-importer inventory --config /source/config/network_importer.toml
Traceback (most recent call last):
  File "/usr/local/bin/network-importer", line 5, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/local/network_importer/cli.py", line 185, in inventory
    ni.build_inventory(limit=limit)
  File "/local/network_importer/performance.py", line 67, in timed
    result = method(*args, **kw)
  File "/local/network_importer/main.py", line 107, in build_inventory
    "conn_timeout": config.SETTINGS.network.conn_timeout,
  File "/usr/local/lib/python3.7/site-packages/nornir/init_nornir.py", line 78, in InitNornir
    **conf.inventory.options,
  File "/usr/local/lib/python3.7/site-packages/nornir/core/deserializer/inventory.py", line 129, in deserialize
    deserialized = cls(*args, **kwargs)
  File "/local/network_importer/inventory.py", line 133, in __init__
    if dev.id != dev.virtual_chassis.master.id:
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by dgarros** [comment]
Thanks for reporting this issue. Before Netbox 2.9, a master was mandatory per virtual chassis, the inventory was assuming that a master will always be present.
I opened #160 to fix this
We hope to published a new release in the next few days
