### ISSUE TITLE
Unable to import data to netbox:  ObjectNotFound: device not present in Netbox

### ISSUE THREAD

**Issue by Kani999** [networktocode/network-importer#171]
### Environment
* Python version: 3.7.7
* Network Importer version: 2.0.0b4

---

Hello,

I'm not able to load data from the network to netbox.

---
I have 1 device in the netbox imported by `onboarding_plugin` 

when I run `network-importer check --config network_importer.toml` the output is:

```
2021-02-15 09:28:48,345 - network-importer - INFO - Import SOT Model
2021-02-15 09:28:48,551 - network-importer - DEBUG - Netbox | Found 1 interfaces for R113-OV
2021-02-15 09:28:48,612 - network-importer - DEBUG - Netbox | Found 1 ip addresses for R113-OV
2021-02-15 09:28:48,628 - network-importer - DEBUG - Netbox | Found 0 cables in netbox for ova-vsb
2021-02-15 09:28:48,628 - network-importer - INFO - Import Network Model
2021-02-15 09:28:49,560 - network-importer - WARNING - Unable to find information for R113-OV in Batfish, SKIPPING
2021-02-15 09:28:49,590 - network-importer - INFO - Collecting cabling information from devices ..
2021-02-15 09:28:49,590 - nornir.core - WARNING - Task 'dispatcher' has not been run – 0 hosts selected
2021-02-15 09:28:49,590 - network-importer - DEBUG - Found 0 cables from Cli
site
  site: ova-vsb MISSING in Network
device
  device: R113-OV MISSING in Network
    interface
      interface: Loopback0 MISSING in Network
        ip_address
          ip_address: 195.132.148.22/32 MISSING in Network
```

In `configs/configs/` folder I have running configuration of the device. `R113-OV.txt`

When I run the inventory command `network-importer inventory --config network_importer.toml`  I Can see the device in the output.
```
- Device Inventory (all)
- Device    ┃ Platform ┃ Reachable ┃ Reason ┃
- R113-OV │ cisco         │ True            │        │
```

If I run `apply` command `network-importer apply --config network_importer.toml`
I end up with the `diffsync.exceptions.ObjectNotFound: device R113-OV not present in Netbox` error
```
2021-02-15 09:35:56,116 - network-importer - INFO - Import SOT Model
2021-02-15 09:35:56,305 - network-importer - DEBUG - Netbox | Found 1 interfaces for R113-OV
2021-02-15 09:35:56,356 - network-importer - DEBUG - Netbox | Found 1 ip addresses for R113-OV
2021-02-15 09:35:56,460 - network-importer - DEBUG - Netbox | Found 0 cables in netbox for ova-vsb
2021-02-15 09:35:56,460 - network-importer - INFO - Import Network Model
2021-02-15 09:35:57,633 - network-importer - WARNING - Unable to find information for R113-OV in Batfish, SKIPPING
2021-02-15 09:35:57,656 - network-importer - INFO - Collecting cabling information from devices ..
2021-02-15 09:35:57,657 - nornir.core - WARNING - Task 'dispatcher' has not been run – 0 hosts selected
2021-02-15 09:35:57,657 - network-importer - DEBUG - Found 0 cables from Cli
Traceback (most recent call last):
  File "/home/jankrupa/deleteme/venv/bin/network-importer", line 8, in <module>
    sys.exit(main())
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/network_importer/cli.py", line 106, in apply
    ni.sync()
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/network_importer/main.py", line 145, in sync
    self.sot.sync_from(self.network, diff_class=NetworkImporterDiff)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/diffsync/__init__.py", line 464, in sync_from
    result = syncer.perform_sync()
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/diffsync/helpers.py", line 251, in perform_sync
    changed |= self.sync_diff_element(element)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/diffsync/helpers.py", line 304, in sync_diff_element
    changed |= self.sync_diff_element(child, parent_model=model)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/diffsync/helpers.py", line 283, in sync_diff_element
    changed, modified_model = self.sync_model(model, ids, attrs)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/diffsync/helpers.py", line 337, in sync_model
    model = model.delete()
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/network_importer/adapters/netbox_api/models.py", line 260, in delete
    dev = self.diffsync.get(self.diffsync.device, identifier=self.device_name)
  File "/home/jankrupa/deleteme/venv/lib/python3.8/site-packages/diffsync/__init__.py", line 567, in get
    raise ObjectNotFound(f"{modelname} {uid} not present in {self.name}")
diffsync.exceptions.ObjectNotFound: device R113-OV not present in Netbox
```

My Configuration file looks like this:

```
[main]

import_ips = true
import_prefixes = false
import_intf_status = false
import_vlans = "config"         # Valid options are ["cli", "config", "no", true, false]
import_cabling = "lldp"         # Valid options are ["lldp", "cdp", "config", "no", true, false]
excluded_platforms_cabling = ["cisco_asa"]

# Directory where the configuration can be find, organized in Batfish format
configs_directory = "configs"

[netbox]
# The information to connect to NetBox needs to be provided, either in the config file or as environment variables
address = "netbox address"                   # Alternative Env Variable : NETBOX_ADDRESS
token = "token"  # Alternative Env Variable : NETBOX_TOKEN
verify_ssl = false                                   # Alternative Env Variable : NETBOX_VERIFY_SSL

[batfish]
address = "localhost"   # Alternative Env Variable : BATFISH_ADDRESS
# api_key = "XXXX"        # Alternative Env Variable : BATFISH_API_KEY
network_name = "network-importer"
snapshot_name = "latest"
port_v1 = 9997
port_v2 = 9996
use_ssl = false

[network]
login = "NAPALM login"          # Alternative Env Variable : NETWORK_DEVICE_LOGIN
password = "NAPALM Password"       # Alternative Env Variable : NETWORK_DEVICE_PWD
enable = true            # Alternative Env Variable : NETWORK_DEVICE_ENABLE

# Connection parameters for Netmiko
global_delay_factor = 5
banner_timeout = 15
conn_timeout = 5

# List of valid FQDN that can be found in the network,
# The FQDNs in this list will be automatically removed from all neighbors discovered from LLDP/CDP
fqdns = [ ]

[inventory]
# The default method is to use the primary IP defined in NetBox.
# As an alternative it's possible to use the name of the device and provide your own FQDN.
use_primary_ip = true # (default: true)

```

---

Thank you 

---

@Kani999 Please can you open a new issue to track this one and provide your configuration file and the output of the cli. thanks

_Originally posted by @dgarros in https://github.com/networktocode/network-importer/issues/164#issuecomment-778165057_

**Comment by Kani999** [comment]
Hello,
I found the problem. I've got corrupted (or unsupported lines) configuration files from point of view of BatFish.

---
To whom who may run into the same issue
- I run through https://batfish.readthedocs.io/en/latest/notebooks/interacting.html
- set up the configuration files as the documentation says and run
```
import pandas as pd
from pybatfish.client.commands import *
from pybatfish.datamodel import *
from pybatfish.datamodel.answer import *
from pybatfish.datamodel.flow import *
from pybatfish.question import *
from pybatfish.question import bfq

from pprint import pprint

bf_session.host = 'localhost'
bf_set_network('example')
SNAPSHOT_DIR = './'
bf_init_snapshot(SNAPSHOT_DIR, name='snapshot-example', overwrite=True)

# This will display save diagnostics, so you can find out what fails
bf_upload_diagnostics(dry_run=True, contact_info='example@test.com')
```
- then when I got through ERRORS (warnings can be ignored from my side), then te importer works fine
-  I just commented ERROR lines in configuration
