### ISSUE TITLE
Import IosXR device - Error reading SSH protocol banner

### ISSUE THREAD

**Issue by Kani999** [networktocode/network-importer#196]
### Environment
* Python version: 3.8.5
* NetBox version:  v2.10.10
* network-importer:  v2.0.0-beta.4

### Steps to Reproduce
1. Onboard iosxr device
2. Run `network-importer inventory` - ok
3. Run `network-importer check`
3. Exceptions occurs 

### Expected Behavior
Network-importer runs without any errors

### Observed Behavior
Network-importer fails with exception `Error reading SSH protocol banner`

---

I found that Netmiko has setting for banner_timeout. So I set up it at configuration file

```yaml
[network]
login = ""          # Alternative Env Variable : NETWORK_DEVICE_LOGIN
password = ""       # Alternative Env Variable : NETWORK_DEVICE_PWD
enable = true               # Alternative Env Variable : NETWORK_DEVICE_ENABLE

# Connection parameters for Netmiko
global_delay_factor = 100
banner_timeout = 200
conn_timeout = 100
```

but it does not seem to work either
---

```log
2021-04-27 07:55:10,532 - network-importer - INFO - Collecting vlans information from devices ..
2021-04-27 07:55:10,533 - network-importer - DEBUG - Executing dispatcher for R199-lab (cisco_xr)
2021-04-27 07:55:10,533 - network-importer - DEBUG - Found driver network_importer.drivers.cisco_default
2021-04-27 07:55:10,535 - network-importer - DEBUG - Executing get_vlans for R199-lab (cisco_xr)
2021-04-27 07:55:10,559 - paramiko.transport - ERROR - Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2021-04-27 07:55:10,562 - paramiko.transport - ERROR - Traceback (most recent call last):
2021-04-27 07:55:10,562 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
2021-04-27 07:55:10,562 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2021-04-27 07:55:10,562 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
2021-04-27 07:55:10,562 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2021-04-27 07:55:10,562 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/packet.py", line 607, in _read_timeout
2021-04-27 07:55:10,562 - paramiko.transport - ERROR -     x = self.__socket.recv(128)
2021-04-27 07:55:10,563 - paramiko.transport - ERROR - ConnectionResetError: [Errno 104] Connection reset by peer
2021-04-27 07:55:10,563 - paramiko.transport - ERROR -
2021-04-27 07:55:10,563 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2021-04-27 07:55:10,563 - paramiko.transport - ERROR -
2021-04-27 07:55:10,563 - paramiko.transport - ERROR - Traceback (most recent call last):
2021-04-27 07:55:10,563 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
2021-04-27 07:55:10,564 - paramiko.transport - ERROR -     self._check_banner()
2021-04-27 07:55:10,564 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
2021-04-27 07:55:10,564 - paramiko.transport - ERROR -     raise SSHException(
2021-04-27 07:55:10,564 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2021-04-27 07:55:10,564 - paramiko.transport - ERROR -
2021-04-27 07:55:10,569 - nornir.core.task - ERROR - Host 'R199-lab': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

...
...
...
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

2021-04-27 07:55:10,569 - network-importer - DEBUG - An exception occured while pulling the vlans information
Traceback (most recent call last):
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/network_importer/drivers/cisco_default.py", line 128, in get_vlans
    results = task.run(task=netmiko_send_command, command_string="show vlan", use_genie=True)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/nornir/core/task.py", line 147, in run
    raise NornirSubTaskError(task=task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: <function netmiko_send_command at 0x7f76dc0c3dc0> (failed)

2021-04-27 07:55:10,570 - nornir.core.task - ERROR - Host 'R199-lab': task 'dispatcher' failed with traceback:
Traceback (most recent call last):
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/network_importer/drivers/__init__.py", line 58, in dispatcher
    result = task.run(task=driver_task)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/nornir/core/task.py", line 147, in run
    raise NornirSubTaskError(task=task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: <function NetworkImporterDriver.get_vlans at 0x7f76b0a1d0d0> (failed)


2021-04-27 07:55:10,570 - network-importer - INFO - Collecting cabling information from devices ..
2021-04-27 07:55:10,571 - network-importer - DEBUG - Executing dispatcher for R199-lab (cisco_xr)
2021-04-27 07:55:10,571 - network-importer - DEBUG - Found driver network_importer.drivers.cisco_default
2021-04-27 07:55:10,571 - network-importer - DEBUG - Executing get_neighbor for R199-lab (cisco_xr)
2021-04-27 07:55:10,592 - paramiko.transport - ERROR - Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2021-04-27 07:55:10,593 - paramiko.transport - ERROR - Traceback (most recent call last):
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/packet.py", line 607, in _read_timeout
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -     x = self.__socket.recv(128)
2021-04-27 07:55:10,593 - paramiko.transport - ERROR - ConnectionResetError: [Errno 104] Connection reset by peer
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -
2021-04-27 07:55:10,593 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -
2021-04-27 07:55:10,593 - paramiko.transport - ERROR - Traceback (most recent call last):
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
2021-04-27 07:55:10,593 - paramiko.transport - ERROR -     self._check_banner()
2021-04-27 07:55:10,594 - paramiko.transport - ERROR -   File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
2021-04-27 07:55:10,594 - paramiko.transport - ERROR -     raise SSHException(
2021-04-27 07:55:10,594 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2021-04-27 07:55:10,594 - paramiko.transport - ERROR -
2021-04-27 07:55:10,594 - nornir.core.task - ERROR - Host 'R199-lab': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

...
...
...

2021-04-27 07:55:10,594 - network-importer - WARNING - R199-lab | Something went wrong while trying to pull the neighbor information
2021-04-27 07:55:10,594 - nornir.core.task - ERROR - Host 'R199-lab': task 'dispatcher' failed with traceback:
Traceback (most recent call last):
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/network_importer/drivers/__init__.py", line 58, in dispatcher
    result = task.run(task=driver_task)
  File "/home/jankrupa/nautobot/network-importer/venv/lib/python3.8/site-packages/nornir/core/task.py", line 147, in run
    raise NornirSubTaskError(task=task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: <function NetworkImporterDriver.get_neighbors at 0x7f76b0a9fdc0> (failed)
```

**Comment by dgarros** [comment]
Would be great to connect to the device with Netmiko outside of the network importer first, from the same host, to see if the connection is working as expected.
and once we have a good configuration for Netmiko, we can work on integrating it into the network importer

**Comment by Kani999** [comment]
```python
from netmiko import ConnectHandler
from jinja2 import Template

def send_command_test(host, username, password, device_type, port=22):
    device_dict = {
        'device_type': device_type,
        'host': host,
        'username': username,
        'password': password,
        'secret': password,
        'port': port
    }

    with ConnectHandler(**device_dict) as conn:
        print("entering enable mode")
        conn.enable()
        print("enable mode on")

        output = conn.send_command('show vrf all detail')

        print(output)
        return output

```

I'm using the code above with the same iosXR device. It's also run from the same machine

- I tried:
    - show ver
    - show vrf all detail
    - show lldp neighbors detail
  
And everything runs without any error.

**Comment by Kani999** [comment]
- Increasing `rate-limit` (from 60 to 120) on the **network device** solved the problem.

**Comment by dgarros** [comment]
Great news, thanks for the update
